### ISSUE TITLE
[Unity 2021.3.14f1] Additional windows.

### ISSUE THREAD

**Issue by RimuruDev** [vavilichev/Lukomor#9]
### Good day. I wanted to know why, after running the example in Unity 2021.3.14f1, 2 additional empty windows are created.
![изображение](https://user-images.githubusercontent.com/85500556/206492159-dad01695-d99e-4c74-966e-89af2666a9e7.png)
![изображение](https://user-images.githubusercontent.com/85500556/206492447-53b83e80-e9c5-4fcb-8d4e-92e1e238184d.png)

**Comment by vavilichev** [comment]
> ### Good day. I wanted to know why, after running the example in Unity 2021.3.14f1, 2 additional empty windows are created.
> ![изображение](https://user-images.githubusercontent.com/85500556/206492159-dad01695-d99e-4c74-966e-89af2666a9e7.png) ![изображение](https://user-images.githubusercontent.com/85500556/206492447-53b83e80-e9c5-4fcb-8d4e-92e1e238184d.png)

You are right, it's a mistake. I upated the asset, but be carreful, I alse made a major update for Lukomor Architecture, and if you already use the asset in your project, your should update by different way. You should reimport asset with a link

```
https://github.com/vavilichev/Lukomor.git#version_2
```

Because major update doesnt support backward compatibility and it will break your project.
